import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/user_model_cheryl.dart';
import '../utility/passwordHash_jabir.dart';

class UserService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Create a new user with hashed password
  Future<bool> createUserWithPassword({
    required String email,
    required String username,
    required String password,
  }) async {
    try {
      // Hash the password
      String hashedPassword = await PasswordHashUtil.hashPassword(password);
      
      // Generate a new document ID for the user
      String newUid = _firestore.collection('users').doc().id;
      
      // Create user profile in Firestore using the existing user model
      UserModelCheryl newUser = UserModelCheryl(
        uid: newUid, // Primary Key (auto-generated by Firestore)
        email: email.trim(), // Validated with @student.univ.ac.id regex
        username: username.trim(), // Display name
        balance: 200000, // Default balance (200000), as specified
        password: hashedPassword, // Store hashed password
      );

      // Create user profile in Firestore with all required fields
      await _firestore.collection('users').doc(newUid).set({
        ...newUser.toMapCheryl(), // Use the model's toMap method
        'createdAt': FieldValue.serverTimestamp(), // Server timestamp for accuracy
      });

      return true;
    } catch (e) {
      print('Error creating user: $e');
      return false;
    }
  }
  
  /// Find user by email and verify password
  Future<UserModelCheryl?> findUserByEmailAndPassword(String email, String password) async {
    try {
      // Find user by email
      QuerySnapshot querySnapshot = await _firestore
          .collection('users')
          .where('email', isEqualTo: email.trim())
          .limit(1)
          .get();
      
      if (querySnapshot.docs.isEmpty) {
        return null; // User not found
      }
      
      // Get the user data
      DocumentSnapshot userDoc = querySnapshot.docs.first;
      UserModelCheryl user = UserModelCheryl.fromMapCheryl(userDoc.data() as Map<String, dynamic>);
      
      print('Retrieved user from DB: ${user.email}, stored hash: ${user.password}'); // Debug log
      // Verify the password
      bool isPasswordValid = await PasswordHashUtil.verifyPassword(password, user.password);

      print('Password verification result: $isPasswordValid'); // Debug log
      if (isPasswordValid) {
        return user; // Return user if password is correct
      } else {
        return null; // Invalid password
      }
    } catch (e) {
      print('Error finding user: $e');
      return null;
    }
  }
  
  /// Check if email already exists
  Future<bool> isEmailExists(String email) async {
    try {
      QuerySnapshot querySnapshot = await _firestore
          .collection('users')
          .where('email', isEqualTo: email.trim())
          .limit(1)
          .get();
      
      return querySnapshot.docs.isNotEmpty;
    } catch (e) {
      print('Error checking email: $e');
      return false;
    }
  }
}