// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIyNNG18SoJp5ktq1WA8hHc9UioOQEmIU',
    appId: '1:4775709450:web:3796c85a1fcf9cbb1a88f3',
    messagingSenderId: '4775709450',
    projectId: 'cinemapro-37004',
    authDomain: 'cinemapro-37004.firebaseapp.com',
    storageBucket: 'cinemapro-37004.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnUKO8j6RX-6L41D5ee_qu8VItwRFNR-k',
    appId: '1:4775709450:android:8146abcab77960221a88f3',
    messagingSenderId: '4775709450',
    projectId: 'cinemapro-37004',
    storageBucket: 'cinemapro-37004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbeEWuMwzobc5AooSSUJ4zPTa3Gigzx20',
    appId: '1:4775709450:ios:4bc62fa63884f8d51a88f3',
    messagingSenderId: '4775709450',
    projectId: 'cinemapro-37004',
    storageBucket: 'cinemapro-37004.firebasestorage.app',
    iosBundleId: 'com.example.cinemapro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbeEWuMwzobc5AooSSUJ4zPTa3Gigzx20',
    appId: '1:4775709450:ios:4bc62fa63884f8d51a88f3',
    messagingSenderId: '4775709450',
    projectId: 'cinemapro-37004',
    storageBucket: 'cinemapro-37004.firebasestorage.app',
    iosBundleId: 'com.example.cinemapro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIyNNG18SoJp5ktq1WA8hHc9UioOQEmIU',
    appId: '1:4775709450:web:9d47d59d47412f901a88f3',
    messagingSenderId: '4775709450',
    projectId: 'cinemapro-37004',
    authDomain: 'cinemapro-37004.firebaseapp.com',
    storageBucket: 'cinemapro-37004.firebasestorage.app',
  );
}
